### PR TITLE
Adds voting authority

### PR DESCRIPTION
**Pull request by mixmasala**

### CODE REVIEW

**Comment by david415** [comment]
it's failing because the authority's s11n module has it's own internal format... and travis was building with authority master branch which doesn't have those new fields you added. in other words, it failed because you asked it to and that's ok. :)

**Comment by mixmasala** [comment]
But this is a pull request for authority which contains those fields, why is travis fetching authority/master ?

**Comment by david415** [comment]
oh no i was wrong. it's failing because core/pki doesn't have those fields.

**Comment by mixmasala** [comment]
core pki master branch does have those fields though

**Pull request merged**
