### PR TITLE
Don't vote for an existing consensus

### PR DESCRIPTION
**Pull request by david415**
i like this change. why have we not yet merged it? do you doubt it's correctness? any objections to merging?

### CODE REVIEW

**Comment by mixmasala** [comment]
The reason I didn't merge it was I hadn't tested it thoroughly yet.

**Comment by david415** [comment]
> The reason I didn't merge it was I hadn't tested it thoroughly yet.

fair enough. we can work together and write tests.

**Comment by david415** [comment]
has this feature been tested yet?

**Comment by mixmasala** [comment]
not tested against current master; not sure this does what we expect

**Comment by david415** [comment]
ok. sounds like current status of this is: DO NOT MERGE UNTIL TESTED.

**Comment by cloehle** [comment]
After trying to test this PR my understanding is that this does nothing.
the fsm cannot be both in stateAcceptDescriptor and try to vote on a consensus that not only exists but the authority has already fetched.
Consensusses are fetched at stateBootstrap and then only the current and past epoch. (and it will skip voting there if it is past mixPublishDeadline).

Because of this I could not reproduce the behavior that this would fix. If it ever did occure as a bug, I guess this was because the deadlines were also wrong, which were fixed at #92

**Pull request closed without merging**
